#!/bin/bash

# 日历授权助手 - 详细步骤指导

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║     📅 日历授权助手 - 详细步骤指导                           ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "当前状态：应用只能访问 'New Jira Assistant' 主日历"
echo ""
echo "需要授权的日历："
echo "  1. new jira (您的个人日历)"
echo "  2. BO Coordinator (Meeting schedules 群组日历)"
echo ""
echo "=========================================="
echo ""
echo "第一步：授权 new jira 日历"
echo "=========================================="
echo ""
echo "操作步骤："
echo ""
echo "1. 打开 Lark 应用（桌面版或网页版）"
echo "   → 网页版: https://www.larksuite.com/"
echo ""
echo "2. 进入 '日历' 应用"
echo "   → 在左侧导航栏点击日历图标"
echo ""
echo "3. 找到 'new jira' 日历"
echo "   → 在左侧日历列表中查找"
echo "   → 如果没有看到，可能需要先创建或订阅"
echo ""
echo "4. 点击日历设置"
echo "   → 点击日历名称旁的 '...' 或设置图标"
echo "   → 选择 '日历设置' 或 'Calendar Settings'"
echo ""
echo "5. 添加应用成员"
echo "   → 找到 '成员' 或 '成员管理' 部分"
echo "   → 点击 '添加成员' 或 'Add Member'"
echo ""
echo "6. 搜索您的应用"
echo "   → 输入 App ID: cli_aa84163b89789ed3"
echo "   → 或搜索应用名称"
echo ""
echo "7. 授予权限"
echo "   → 选择 '编辑者' 或 'Editor' 权限"
echo "   → 点击 '确定' 或 '添加'"
echo ""
echo "=========================================="
echo ""
echo "第二步：授权 BO Coordinator 日历"
echo "=========================================="
echo ""
echo "操作步骤："
echo ""
echo "1. 进入 Meeting schedules 群组"
echo "   → 在 Lark 左侧找到群组列表"
echo "   → 点击进入 'Meeting schedules' 群组"
echo ""
echo "2. 找到群组日历"
echo "   → 在群组信息中查找日历"
echo "   → 或在日历应用中找到 'BO Coordinator' 日历"
echo ""
echo "3. 进入日历设置"
echo "   → 点击 BO Coordinator 日历的 '...' 菜单"
echo "   → 选择 '日历设置'"
echo ""
echo "4. 添加应用成员"
echo "   → 找到 '成员管理' 或 '权限管理'"
echo "   → 点击 '添加成员'"
echo ""
echo "5. 搜索并添加应用"
echo "   → 输入 App ID: cli_aa84163b89789ed3"
echo "   → 找到应用后点击添加"
echo ""
echo "6. 设置权限"
echo "   → 授予 '编辑者' 权限"
echo "   → 确保可以读取和创建事件"
echo ""
echo "7. 保存设置"
echo "   → 点击 '保存' 或 '确定'"
echo ""
echo "=========================================="
echo ""
echo "第三步：验证授权"
echo "=========================================="
echo ""
echo "授权完成后，等待 2-3 分钟，然后运行："
echo ""
echo "  cd '/Users/Lark CLI/vantageUm_Calendar'"
echo "  ./list-calendars.sh"
echo ""
echo "预期结果："
echo "  ✅ new jira 日历出现在列表中"
echo "  ✅ BO Coordinator 日历出现在列表中"
echo ""
echo "=========================================="
echo ""
echo "第四步：读取日历事件"
echo "=========================================="
echo ""
echo "授权成功后，运行以下命令读取日历事件："
echo ""
echo "  cd '/Users/Lark CLI/vantageUm_Calendar'"
echo "  ./read-calendars.sh"
echo ""
echo "=========================================="
echo ""
echo "💡 提示"
echo "=========================================="
echo ""
echo "如果找不到日历："
echo "  1. 确认日历名称是否正确"
echo "  2. 检查日历是否已创建"
echo "  3. 确认您有访问权限"
echo ""
echo "如果找不到应用："
echo "  1. 确认应用已发布"
echo "  2. 使用正确的 App ID: cli_aa84163b89789ed3"
echo "  3. 尝试使用应用名称搜索"
echo ""
echo "=========================================="
echo ""
echo "准备好了吗？请按照上述步骤操作！"
echo ""
echo "完成后，告诉我结果，我会帮您验证和读取日历。"
echo ""