#!/bin/bash

# 日历 ID 验证脚本
# 此脚本帮助您验证 Lark 日历 ID 是否正确

echo "=========================================="
echo "   日历 ID 验证工具"
echo "=========================================="
echo ""
echo "当前配置的日历 ID:"
echo ""
echo "Bo Coordinator: ou_c6bdc791b875c3af1775a652bcf3b638"
echo "new jira:       ou_dc36b8ad99537b07510b9af57d152136"
echo ""
echo "=========================================="
echo ""
echo "请按照以下步骤验证日历 ID:"
echo ""
echo "步骤 1: 打开 Lark 日历应用"
echo "步骤 2: 找到 Bo Coordinator 日历"
echo "步骤 3: 点击日历设置（...菜单）"
echo "步骤 4: 查看日历 ID"
echo "步骤 5: 对比上面的 ID 是否一致"
echo ""
echo "步骤 6: 对 new jira 日历重复以上步骤"
echo ""
echo "=========================================="
echo ""
echo "如果日历 ID 不一致，请执行以下命令更新:"
echo ""
echo "# 更新 Bo Coordinator 日历 ID"
echo "gh variable set BO_COORDINATOR_CALENDAR_ID \\"
echo "  --body \"ou_您的实际日历ID\" \\"
echo "  --repo newjira1994-spec/vantageUm_Calendar"
echo ""
echo "# 更新 new jira 日历 ID"
echo "gh variable set NEW_JIRA_CALENDAR_ID \\"
echo "  --body \"ou_您的实际日历ID\" \\"
echo "  --repo newjira1994-spec/vantageUm_Calendar"
echo ""
echo "=========================================="
